version: '2'
services:
  kibana: 
    image: docker.elastic.co/kibana/kibana:5.1.2
    # volumes: 
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    ports:
      - 9200:9200

